### ISSUE TITLE
Compatibility with M-76 module

### ISSUE THREAD

**Issue by dvoc** [dave-code-ruiz/uhomeuponor#33]
Hello, I'm owner of a M-76 module with C-56 controller, and seems that the API is not compatible.
Error from HA:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/uhomeuponor/climate.py", line 43, in async_setup_entry
    return await async_setup_climate(
  File "/config/custom_components/uhomeuponor/climate.py", line 60, in async_setup_climate
    await uponor.rescan()
  File "/config/custom_components/uhomeuponor/uponor_api/__init__.py", line 41, in rescan
    await self.init_controllers()
  File "/config/custom_components/uhomeuponor/uponor_api/__init__.py", line 57, in init_controllers
    if bitMask & mask:
TypeError: unsupported operand type(s) for &: 'float' and 'int'

Any possibility to update the code to be compatible with this module? I can debug if needed.
Thank you

**Comment by dave-code-ruiz** [comment]
sorry , it is not compatible, and it is not possible do it.
